// Package events defines the cluster event type shared by all Clusdr engines.
//
// This package has no internal imports intentionally: both membership and
// consensus engines import it to emit events without creating circular deps.
package events

import "time"

// Built-in event types emitted by Clusdr engines.
const (
	TypeMemberJoin    = "member.join"
	TypeMemberDead    = "member.dead"
	TypeMemberLeft    = "member.left"
	TypeLeaderChanged = "leader.changed"
	TypeLockExpired   = "lock.expired"
	TypeLeaseGranted  = "lease.granted"
	TypeLeaseExpired  = "lease.expired"
	TypeLeaseRevoked  = "lease.revoked"

	// Protocol events generated by the Watch layer.
	// Always delivered, even when the client filters event types.
	TypeWatchSync = "watch.sync" // snapshot complete; Seq is the bus high-water mark
	TypeWatchGap  = "watch.gap"  // client missed Seq range; payload {"from":N,"to":M}

	// TypeCustomPrefix is prepended to user topics.
	// A publish of topic "deployment" becomes type "custom.deployment".
	TypeCustomPrefix = "custom."
)

// Event is a single occurrence within the cluster. Its shape matches the
// Watch API proto so it can be forwarded to gRPC streams without conversion.
type Event struct {
	// Type is a dot-separated string: "member.join", "member.dead",
	// "member.left", "leader.changed", "lock.expired", "lease.granted".
	Type string

	// Source is the node ID responsible for the event.
	Source string

	// Payload is optional JSON-encoded event detail. Consumers that only need
	// the Type and Source may leave this empty.
	Payload []byte

	// Timestamp is when the event was created.
	Timestamp time.Time

	// Seq is a cluster-wide monotonically increasing sequence number assigned
	// by the event bus. Used for gap detection on Watch reconnect.
	Seq uint64
}
