// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.9
// source: clusdr/v1alpha1/events.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// topic is the routing key. The Watch type becomes "custom.<topic>".
	// Allowed characters: A-Z a-z 0-9 . _ -  (1–128 chars).
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// payload is an opaque application blob. Max 64 KiB.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// event_id is a unique id used to suppress duplicates on retry/fan-out.
	// Empty on a client call; the receiving node generates one.
	EventId string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// source is the originating node id. Empty on a client call; filled by
	// the first node that accepts the publish.
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// relay is true on node-to-node fan-out. Relayed events are emitted
	// locally but not forwarded again (prevents publish storms).
	Relay         bool `protobuf:"varint,5,opt,name=relay,proto3" json:"relay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_clusdr_v1alpha1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PublishEventRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PublishEventRequest) GetRelay() bool {
	if x != nil {
		return x.Relay
	}
	return false
}

type PublishEventResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EventId  string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// type is the Watch event type, e.g. "custom.deployment".
	Type          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_clusdr_v1alpha1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_events_proto_rawDescGZIP(), []int{1}
}

func (x *PublishEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PublishEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishEventResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_clusdr_v1alpha1_events_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_events_proto_rawDesc = "" +
	"\n" +
	"\x1cclusdr/v1alpha1/events.proto\x12\x0fclusdr.v1alpha1\"\x8e\x01\n" +
	"\x13PublishEventRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05relay\x18\x05 \x01(\bR\x05relay\"{\n" +
	"\x14PublishEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type2k\n" +
	"\fEventService\x12[\n" +
	"\fPublishEvent\x12$.clusdr.v1alpha1.PublishEventRequest\x1a%.clusdr.v1alpha1.PublishEventResponseB>Z<github.com/durguto/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_events_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_events_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_events_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_events_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_events_proto_rawDesc), len(file_clusdr_v1alpha1_events_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_events_proto_rawDescData
}

var file_clusdr_v1alpha1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clusdr_v1alpha1_events_proto_goTypes = []any{
	(*PublishEventRequest)(nil),  // 0: clusdr.v1alpha1.PublishEventRequest
	(*PublishEventResponse)(nil), // 1: clusdr.v1alpha1.PublishEventResponse
}
var file_clusdr_v1alpha1_events_proto_depIdxs = []int32{
	0, // 0: clusdr.v1alpha1.EventService.PublishEvent:input_type -> clusdr.v1alpha1.PublishEventRequest
	1, // 1: clusdr.v1alpha1.EventService.PublishEvent:output_type -> clusdr.v1alpha1.PublishEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_events_proto_init() }
func file_clusdr_v1alpha1_events_proto_init() {
	if File_clusdr_v1alpha1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_events_proto_rawDesc), len(file_clusdr_v1alpha1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_events_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_events_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_events_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_events_proto = out.File
	file_clusdr_v1alpha1_events_proto_goTypes = nil
	file_clusdr_v1alpha1_events_proto_depIdxs = nil
}
