// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.9
// source: clusdr/v1alpha1/health.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_clusdr_v1alpha1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_health_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id is the unique identifier of this node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// cluster_id is the cluster this node belongs to.
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// role is the current role of this node (standalone | follower | leader).
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// healthy is true when the node is running and reachable.
	Healthy       bool `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_clusdr_v1alpha1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *HealthResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_clusdr_v1alpha1_health_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_health_proto_rawDesc = "" +
	"\n" +
	"\x1cclusdr/v1alpha1/health.proto\x12\x0fclusdr.v1alpha1\"\x0f\n" +
	"\rHealthRequest\"v\n" +
	"\x0eHealthResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy2Z\n" +
	"\rHealthService\x12I\n" +
	"\x06Health\x12\x1e.clusdr.v1alpha1.HealthRequest\x1a\x1f.clusdr.v1alpha1.HealthResponseB>Z<github.com/durguto/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_health_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_health_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_health_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_health_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_health_proto_rawDesc), len(file_clusdr_v1alpha1_health_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_health_proto_rawDescData
}

var file_clusdr_v1alpha1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clusdr_v1alpha1_health_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: clusdr.v1alpha1.HealthRequest
	(*HealthResponse)(nil), // 1: clusdr.v1alpha1.HealthResponse
}
var file_clusdr_v1alpha1_health_proto_depIdxs = []int32{
	0, // 0: clusdr.v1alpha1.HealthService.Health:input_type -> clusdr.v1alpha1.HealthRequest
	1, // 1: clusdr.v1alpha1.HealthService.Health:output_type -> clusdr.v1alpha1.HealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_health_proto_init() }
func file_clusdr_v1alpha1_health_proto_init() {
	if File_clusdr_v1alpha1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_health_proto_rawDesc), len(file_clusdr_v1alpha1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_health_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_health_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_health_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_health_proto = out.File
	file_clusdr_v1alpha1_health_proto_goTypes = nil
	file_clusdr_v1alpha1_health_proto_depIdxs = nil
}
