// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.9
// source: clusdr/v1alpha1/heartbeat.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender_id is the node ID of the pinging node.
	SenderId      string `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_clusdr_v1alpha1_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id is the responding node's ID.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Alive         bool   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_clusdr_v1alpha1_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

var File_clusdr_v1alpha1_heartbeat_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x1fclusdr/v1alpha1/heartbeat.proto\x12\x0fclusdr.v1alpha1\"*\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\"=\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive2W\n" +
	"\x10HeartbeatService\x12C\n" +
	"\x04Ping\x12\x1c.clusdr.v1alpha1.PingRequest\x1a\x1d.clusdr.v1alpha1.PingResponseB>Z<github.com/durguto/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_heartbeat_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_heartbeat_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_heartbeat_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_heartbeat_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_heartbeat_proto_rawDesc), len(file_clusdr_v1alpha1_heartbeat_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_heartbeat_proto_rawDescData
}

var file_clusdr_v1alpha1_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clusdr_v1alpha1_heartbeat_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: clusdr.v1alpha1.PingRequest
	(*PingResponse)(nil), // 1: clusdr.v1alpha1.PingResponse
}
var file_clusdr_v1alpha1_heartbeat_proto_depIdxs = []int32{
	0, // 0: clusdr.v1alpha1.HeartbeatService.Ping:input_type -> clusdr.v1alpha1.PingRequest
	1, // 1: clusdr.v1alpha1.HeartbeatService.Ping:output_type -> clusdr.v1alpha1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_heartbeat_proto_init() }
func file_clusdr_v1alpha1_heartbeat_proto_init() {
	if File_clusdr_v1alpha1_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_heartbeat_proto_rawDesc), len(file_clusdr_v1alpha1_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_heartbeat_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_heartbeat_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_heartbeat_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_heartbeat_proto = out.File
	file_clusdr_v1alpha1_heartbeat_proto_goTypes = nil
	file_clusdr_v1alpha1_heartbeat_proto_depIdxs = nil
}
