// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: clusdr/v1alpha1/join.proto

package clusdrv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JoinService_Join_FullMethodName    = "/clusdr.v1alpha1.JoinService/Join"
	JoinService_Promote_FullMethodName = "/clusdr.v1alpha1.JoinService/Promote"
	JoinService_Leave_FullMethodName   = "/clusdr.v1alpha1.JoinService/Leave"
	JoinService_Rejoin_FullMethodName  = "/clusdr.v1alpha1.JoinService/Rejoin"
)

// JoinServiceClient is the client API for JoinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JoinService handles node-to-node join requests.
// A joining node calls this on an existing cluster member.
type JoinServiceClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// Promote turns an existing observer into a voter. Followers forward to the leader.
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	// Leave is the only Raft RemoveServer. Presence expiry does not call this.
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
	// Rejoin marks an existing Raft server alive again (same id, no AddVoter).
	Rejoin(ctx context.Context, in *RejoinRequest, opts ...grpc.CallOption) (*RejoinResponse, error)
}

type joinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJoinServiceClient(cc grpc.ClientConnInterface) JoinServiceClient {
	return &joinServiceClient{cc}
}

func (c *joinServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, JoinService_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joinServiceClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, JoinService_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joinServiceClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, JoinService_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *joinServiceClient) Rejoin(ctx context.Context, in *RejoinRequest, opts ...grpc.CallOption) (*RejoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejoinResponse)
	err := c.cc.Invoke(ctx, JoinService_Rejoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoinServiceServer is the server API for JoinService service.
// All implementations must embed UnimplementedJoinServiceServer
// for forward compatibility.
//
// JoinService handles node-to-node join requests.
// A joining node calls this on an existing cluster member.
type JoinServiceServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// Promote turns an existing observer into a voter. Followers forward to the leader.
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	// Leave is the only Raft RemoveServer. Presence expiry does not call this.
	Leave(context.Context, *LeaveRequest) (*LeaveResponse, error)
	// Rejoin marks an existing Raft server alive again (same id, no AddVoter).
	Rejoin(context.Context, *RejoinRequest) (*RejoinResponse, error)
	mustEmbedUnimplementedJoinServiceServer()
}

// UnimplementedJoinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJoinServiceServer struct{}

func (UnimplementedJoinServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedJoinServiceServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedJoinServiceServer) Leave(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedJoinServiceServer) Rejoin(context.Context, *RejoinRequest) (*RejoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rejoin not implemented")
}
func (UnimplementedJoinServiceServer) mustEmbedUnimplementedJoinServiceServer() {}
func (UnimplementedJoinServiceServer) testEmbeddedByValue()                     {}

// UnsafeJoinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoinServiceServer will
// result in compilation errors.
type UnsafeJoinServiceServer interface {
	mustEmbedUnimplementedJoinServiceServer()
}

func RegisterJoinServiceServer(s grpc.ServiceRegistrar, srv JoinServiceServer) {
	// If the following call panics, it indicates UnimplementedJoinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JoinService_ServiceDesc, srv)
}

func _JoinService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoinService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinService_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinServiceServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoinService_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinServiceServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinService_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinServiceServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JoinService_Rejoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoinServiceServer).Rejoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JoinService_Rejoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoinServiceServer).Rejoin(ctx, req.(*RejoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JoinService_ServiceDesc is the grpc.ServiceDesc for JoinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clusdr.v1alpha1.JoinService",
	HandlerType: (*JoinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _JoinService_Join_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _JoinService_Promote_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _JoinService_Leave_Handler,
		},
		{
			MethodName: "Rejoin",
			Handler:    _JoinService_Rejoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clusdr/v1alpha1/join.proto",
}

const (
	ControlService_RequestJoin_FullMethodName    = "/clusdr.v1alpha1.ControlService/RequestJoin"
	ControlService_RequestPromote_FullMethodName = "/clusdr.v1alpha1.ControlService/RequestPromote"
	ControlService_RequestLeave_FullMethodName   = "/clusdr.v1alpha1.ControlService/RequestLeave"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlService handles operator commands from the CLI to the local daemon.
type ControlServiceClient interface {
	// RequestJoin tells the local daemon to join the cluster at addr.
	RequestJoin(ctx context.Context, in *RequestJoinRequest, opts ...grpc.CallOption) (*RequestJoinResponse, error)
	// RequestPromote asks the local daemon to promote a node (empty id = self).
	RequestPromote(ctx context.Context, in *RequestPromoteRequest, opts ...grpc.CallOption) (*RequestPromoteResponse, error)
	// RequestLeave asks the local daemon to remove a member from Raft (empty id = self).
	RequestLeave(ctx context.Context, in *RequestLeaveRequest, opts ...grpc.CallOption) (*RequestLeaveResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) RequestJoin(ctx context.Context, in *RequestJoinRequest, opts ...grpc.CallOption) (*RequestJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestJoinResponse)
	err := c.cc.Invoke(ctx, ControlService_RequestJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RequestPromote(ctx context.Context, in *RequestPromoteRequest, opts ...grpc.CallOption) (*RequestPromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPromoteResponse)
	err := c.cc.Invoke(ctx, ControlService_RequestPromote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RequestLeave(ctx context.Context, in *RequestLeaveRequest, opts ...grpc.CallOption) (*RequestLeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestLeaveResponse)
	err := c.cc.Invoke(ctx, ControlService_RequestLeave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
//
// ControlService handles operator commands from the CLI to the local daemon.
type ControlServiceServer interface {
	// RequestJoin tells the local daemon to join the cluster at addr.
	RequestJoin(context.Context, *RequestJoinRequest) (*RequestJoinResponse, error)
	// RequestPromote asks the local daemon to promote a node (empty id = self).
	RequestPromote(context.Context, *RequestPromoteRequest) (*RequestPromoteResponse, error)
	// RequestLeave asks the local daemon to remove a member from Raft (empty id = self).
	RequestLeave(context.Context, *RequestLeaveRequest) (*RequestLeaveResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) RequestJoin(context.Context, *RequestJoinRequest) (*RequestJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestJoin not implemented")
}
func (UnimplementedControlServiceServer) RequestPromote(context.Context, *RequestPromoteRequest) (*RequestPromoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPromote not implemented")
}
func (UnimplementedControlServiceServer) RequestLeave(context.Context, *RequestLeaveRequest) (*RequestLeaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestLeave not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_RequestJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RequestJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RequestJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RequestJoin(ctx, req.(*RequestJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RequestPromote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RequestPromote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RequestPromote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RequestPromote(ctx, req.(*RequestPromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RequestLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestLeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RequestLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RequestLeave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RequestLeave(ctx, req.(*RequestLeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clusdr.v1alpha1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestJoin",
			Handler:    _ControlService_RequestJoin_Handler,
		},
		{
			MethodName: "RequestPromote",
			Handler:    _ControlService_RequestPromote_Handler,
		},
		{
			MethodName: "RequestLeave",
			Handler:    _ControlService_RequestLeave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clusdr/v1alpha1/join.proto",
}
