// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.9
// source: clusdr/v1alpha1/join.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id is the unique ID of the joining node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// cluster_id must match the target cluster's ID; rejected otherwise.
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// address is the gRPC Runtime API address of the joining node.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// raft_addr is the Raft TCP address of the joining node.
	// Required for the leader to call AddVoter.
	RaftAddr string `protobuf:"bytes,4,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	// join_token is the cluster join token from `clusdr init`.
	// Required on the first (non-relay) Join when the cluster has a token hash.
	JoinToken string `protobuf:"bytes,5,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	// relay is set when a follower forwards Join to the leader so the
	// destination does not forward again. Token checks still apply.
	Relay bool `protobuf:"varint,6,opt,name=relay,proto3" json:"relay,omitempty"`
	// observer is true when the joiner should be a Raft non-voter.
	// Empty/false means voter. Does not change quorum.
	Observer      bool `protobuf:"varint,7,opt,name=observer,proto3" json:"observer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JoinRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *JoinRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *JoinRequest) GetRelay() bool {
	if x != nil {
		return x.Relay
	}
	return false
}

func (x *JoinRequest) GetObserver() bool {
	if x != nil {
		return x.Observer
	}
	return false
}

type JoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// accepted is true when the join was granted.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// message carries the rejection reason when accepted is false.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// members is the current cluster member list sent to the joining node.
	Members []*Member `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	// node_cert / node_key are a PEM certificate issued by the cluster CA
	// for the joining node. Empty on relayed joins.
	NodeCert []byte `protobuf:"bytes,4,opt,name=node_cert,json=nodeCert,proto3" json:"node_cert,omitempty"`
	NodeKey  []byte `protobuf:"bytes,5,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	// ca_cert is the cluster CA certificate (PEM). Install it as the trust root.
	CaCert []byte `protobuf:"bytes,6,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	// join_token_hash is the SHA-256 of the cluster join token so the new
	// node can validate future joiners.
	JoinTokenHash []byte `protobuf:"bytes,7,opt,name=join_token_hash,json=joinTokenHash,proto3" json:"join_token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *JoinResponse) GetNodeCert() []byte {
	if x != nil {
		return x.NodeCert
	}
	return nil
}

func (x *JoinResponse) GetNodeKey() []byte {
	if x != nil {
		return x.NodeKey
	}
	return nil
}

func (x *JoinResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *JoinResponse) GetJoinTokenHash() []byte {
	if x != nil {
		return x.JoinTokenHash
	}
	return nil
}

type RequestJoinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// addr is the gRPC Runtime API address of any existing cluster member.
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// token is the cluster join token printed by `clusdr init`.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// observer is true when the local daemon should join as a Raft non-voter.
	Observer      bool `protobuf:"varint,3,opt,name=observer,proto3" json:"observer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJoinRequest) Reset() {
	*x = RequestJoinRequest{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJoinRequest) ProtoMessage() {}

func (x *RequestJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJoinRequest.ProtoReflect.Descriptor instead.
func (*RequestJoinRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{2}
}

func (x *RequestJoinRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RequestJoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestJoinRequest) GetObserver() bool {
	if x != nil {
		return x.Observer
	}
	return false
}

type RequestJoinResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Joined  bool                   `protobuf:"varint,1,opt,name=joined,proto3" json:"joined,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// members is the cluster state after joining.
	Members []*Member `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	// cert_issued is true when the cluster returned a node certificate.
	CertIssued    bool `protobuf:"varint,4,opt,name=cert_issued,json=certIssued,proto3" json:"cert_issued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJoinResponse) Reset() {
	*x = RequestJoinResponse{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJoinResponse) ProtoMessage() {}

func (x *RequestJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJoinResponse.ProtoReflect.Descriptor instead.
func (*RequestJoinResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{3}
}

func (x *RequestJoinResponse) GetJoined() bool {
	if x != nil {
		return x.Joined
	}
	return false
}

func (x *RequestJoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestJoinResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RequestJoinResponse) GetCertIssued() bool {
	if x != nil {
		return x.CertIssued
	}
	return false
}

type PromoteRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// relay is set when a follower forwards Promote to the leader.
	Relay         bool `protobuf:"varint,2,opt,name=relay,proto3" json:"relay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRequest) Reset() {
	*x = PromoteRequest{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRequest) ProtoMessage() {}

func (x *PromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRequest.ProtoReflect.Descriptor instead.
func (*PromoteRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{4}
}

func (x *PromoteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PromoteRequest) GetRelay() bool {
	if x != nil {
		return x.Relay
	}
	return false
}

type PromoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promoted      bool                   `protobuf:"varint,1,opt,name=promoted,proto3" json:"promoted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Members       []*Member              `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteResponse) Reset() {
	*x = PromoteResponse{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteResponse) ProtoMessage() {}

func (x *PromoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteResponse.ProtoReflect.Descriptor instead.
func (*PromoteResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{5}
}

func (x *PromoteResponse) GetPromoted() bool {
	if x != nil {
		return x.Promoted
	}
	return false
}

func (x *PromoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PromoteResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type RequestPromoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node_id is the member to promote. Empty means the local node.
	NodeId        string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPromoteRequest) Reset() {
	*x = RequestPromoteRequest{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPromoteRequest) ProtoMessage() {}

func (x *RequestPromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPromoteRequest.ProtoReflect.Descriptor instead.
func (*RequestPromoteRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{6}
}

func (x *RequestPromoteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RequestPromoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promoted      bool                   `protobuf:"varint,1,opt,name=promoted,proto3" json:"promoted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Members       []*Member              `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPromoteResponse) Reset() {
	*x = RequestPromoteResponse{}
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPromoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPromoteResponse) ProtoMessage() {}

func (x *RequestPromoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_join_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPromoteResponse.ProtoReflect.Descriptor instead.
func (*RequestPromoteResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_join_proto_rawDescGZIP(), []int{7}
}

func (x *RequestPromoteResponse) GetPromoted() bool {
	if x != nil {
		return x.Promoted
	}
	return false
}

func (x *RequestPromoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestPromoteResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_clusdr_v1alpha1_join_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_join_proto_rawDesc = "" +
	"\n" +
	"\x1aclusdr/v1alpha1/join.proto\x12\x0fclusdr.v1alpha1\x1a clusdr/v1alpha1/membership.proto\"\xcd\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1b\n" +
	"\traft_addr\x18\x04 \x01(\tR\braftAddr\x12\x1d\n" +
	"\n" +
	"join_token\x18\x05 \x01(\tR\tjoinToken\x12\x14\n" +
	"\x05relay\x18\x06 \x01(\bR\x05relay\x12\x1a\n" +
	"\bobserver\x18\a \x01(\bR\bobserver\"\xf0\x01\n" +
	"\fJoinResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\amembers\x18\x03 \x03(\v2\x17.clusdr.v1alpha1.MemberR\amembers\x12\x1b\n" +
	"\tnode_cert\x18\x04 \x01(\fR\bnodeCert\x12\x19\n" +
	"\bnode_key\x18\x05 \x01(\fR\anodeKey\x12\x17\n" +
	"\aca_cert\x18\x06 \x01(\fR\x06caCert\x12&\n" +
	"\x0fjoin_token_hash\x18\a \x01(\fR\rjoinTokenHash\"Z\n" +
	"\x12RequestJoinRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bobserver\x18\x03 \x01(\bR\bobserver\"\x9b\x01\n" +
	"\x13RequestJoinResponse\x12\x16\n" +
	"\x06joined\x18\x01 \x01(\bR\x06joined\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\amembers\x18\x03 \x03(\v2\x17.clusdr.v1alpha1.MemberR\amembers\x12\x1f\n" +
	"\vcert_issued\x18\x04 \x01(\bR\n" +
	"certIssued\"?\n" +
	"\x0ePromoteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05relay\x18\x02 \x01(\bR\x05relay\"z\n" +
	"\x0fPromoteResponse\x12\x1a\n" +
	"\bpromoted\x18\x01 \x01(\bR\bpromoted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\amembers\x18\x03 \x03(\v2\x17.clusdr.v1alpha1.MemberR\amembers\"0\n" +
	"\x15RequestPromoteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x81\x01\n" +
	"\x16RequestPromoteResponse\x12\x1a\n" +
	"\bpromoted\x18\x01 \x01(\bR\bpromoted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\amembers\x18\x03 \x03(\v2\x17.clusdr.v1alpha1.MemberR\amembers2\xa0\x01\n" +
	"\vJoinService\x12C\n" +
	"\x04Join\x12\x1c.clusdr.v1alpha1.JoinRequest\x1a\x1d.clusdr.v1alpha1.JoinResponse\x12L\n" +
	"\aPromote\x12\x1f.clusdr.v1alpha1.PromoteRequest\x1a .clusdr.v1alpha1.PromoteResponse2\xcd\x01\n" +
	"\x0eControlService\x12X\n" +
	"\vRequestJoin\x12#.clusdr.v1alpha1.RequestJoinRequest\x1a$.clusdr.v1alpha1.RequestJoinResponse\x12a\n" +
	"\x0eRequestPromote\x12&.clusdr.v1alpha1.RequestPromoteRequest\x1a'.clusdr.v1alpha1.RequestPromoteResponseB=Z;github.com/clusdr/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_join_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_join_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_join_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_join_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_join_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_join_proto_rawDesc), len(file_clusdr_v1alpha1_join_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_join_proto_rawDescData
}

var file_clusdr_v1alpha1_join_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_clusdr_v1alpha1_join_proto_goTypes = []any{
	(*JoinRequest)(nil),            // 0: clusdr.v1alpha1.JoinRequest
	(*JoinResponse)(nil),           // 1: clusdr.v1alpha1.JoinResponse
	(*RequestJoinRequest)(nil),     // 2: clusdr.v1alpha1.RequestJoinRequest
	(*RequestJoinResponse)(nil),    // 3: clusdr.v1alpha1.RequestJoinResponse
	(*PromoteRequest)(nil),         // 4: clusdr.v1alpha1.PromoteRequest
	(*PromoteResponse)(nil),        // 5: clusdr.v1alpha1.PromoteResponse
	(*RequestPromoteRequest)(nil),  // 6: clusdr.v1alpha1.RequestPromoteRequest
	(*RequestPromoteResponse)(nil), // 7: clusdr.v1alpha1.RequestPromoteResponse
	(*Member)(nil),                 // 8: clusdr.v1alpha1.Member
}
var file_clusdr_v1alpha1_join_proto_depIdxs = []int32{
	8, // 0: clusdr.v1alpha1.JoinResponse.members:type_name -> clusdr.v1alpha1.Member
	8, // 1: clusdr.v1alpha1.RequestJoinResponse.members:type_name -> clusdr.v1alpha1.Member
	8, // 2: clusdr.v1alpha1.PromoteResponse.members:type_name -> clusdr.v1alpha1.Member
	8, // 3: clusdr.v1alpha1.RequestPromoteResponse.members:type_name -> clusdr.v1alpha1.Member
	0, // 4: clusdr.v1alpha1.JoinService.Join:input_type -> clusdr.v1alpha1.JoinRequest
	4, // 5: clusdr.v1alpha1.JoinService.Promote:input_type -> clusdr.v1alpha1.PromoteRequest
	2, // 6: clusdr.v1alpha1.ControlService.RequestJoin:input_type -> clusdr.v1alpha1.RequestJoinRequest
	6, // 7: clusdr.v1alpha1.ControlService.RequestPromote:input_type -> clusdr.v1alpha1.RequestPromoteRequest
	1, // 8: clusdr.v1alpha1.JoinService.Join:output_type -> clusdr.v1alpha1.JoinResponse
	5, // 9: clusdr.v1alpha1.JoinService.Promote:output_type -> clusdr.v1alpha1.PromoteResponse
	3, // 10: clusdr.v1alpha1.ControlService.RequestJoin:output_type -> clusdr.v1alpha1.RequestJoinResponse
	7, // 11: clusdr.v1alpha1.ControlService.RequestPromote:output_type -> clusdr.v1alpha1.RequestPromoteResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_join_proto_init() }
func file_clusdr_v1alpha1_join_proto_init() {
	if File_clusdr_v1alpha1_join_proto != nil {
		return
	}
	file_clusdr_v1alpha1_membership_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_join_proto_rawDesc), len(file_clusdr_v1alpha1_join_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_clusdr_v1alpha1_join_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_join_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_join_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_join_proto = out.File
	file_clusdr_v1alpha1_join_proto_goTypes = nil
	file_clusdr_v1alpha1_join_proto_depIdxs = nil
}
