// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.9
// source: clusdr/v1alpha1/leases.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lease identity (1–128 chars: letters, digits, . _ -).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// owner is the node or client id. Empty → this daemon's node id.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// ttl_ms is the grant lifetime. 0 uses the daemon default (lease.ttl).
	TtlMs         int64 `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantLeaseRequest) Reset() {
	*x = GrantLeaseRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantLeaseRequest) ProtoMessage() {}

func (x *GrantLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantLeaseRequest.ProtoReflect.Descriptor instead.
func (*GrantLeaseRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{0}
}

func (x *GrantLeaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrantLeaseRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GrantLeaseRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type GrantLeaseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Granted        bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Owner          string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrantLeaseResponse) Reset() {
	*x = GrantLeaseResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantLeaseResponse) ProtoMessage() {}

func (x *GrantLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantLeaseResponse.ProtoReflect.Descriptor instead.
func (*GrantLeaseResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{1}
}

func (x *GrantLeaseResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *GrantLeaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GrantLeaseResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *GrantLeaseResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GrantLeaseResponse) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type RenewLeaseRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner        string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FencingToken uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// ttl_ms replaces the remaining lifetime. 0 reuses the original TTL.
	TtlMs         int64 `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{2}
}

func (x *RenewLeaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenewLeaseRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RenewLeaseRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *RenewLeaseRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type RenewLeaseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Renewed        bool                   `protobuf:"varint,1,opt,name=renewed,proto3" json:"renewed,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,4,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{3}
}

func (x *RenewLeaseResponse) GetRenewed() bool {
	if x != nil {
		return x.Renewed
	}
	return false
}

func (x *RenewLeaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RenewLeaseResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *RenewLeaseResponse) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type RevokeLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLeaseRequest) Reset() {
	*x = RevokeLeaseRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLeaseRequest) ProtoMessage() {}

func (x *RevokeLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLeaseRequest.ProtoReflect.Descriptor instead.
func (*RevokeLeaseRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeLeaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RevokeLeaseRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RevokeLeaseRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type RevokeLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeLeaseResponse) Reset() {
	*x = RevokeLeaseResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeLeaseResponse) ProtoMessage() {}

func (x *RevokeLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeLeaseResponse.ProtoReflect.Descriptor instead.
func (*RevokeLeaseResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeLeaseResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeLeaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListLeasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesRequest) Reset() {
	*x = ListLeasesRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesRequest) ProtoMessage() {}

func (x *ListLeasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesRequest.ProtoReflect.Descriptor instead.
func (*ListLeasesRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{6}
}

type LeaseInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner          string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	GrantedUnixMs  int64                  `protobuf:"varint,4,opt,name=granted_unix_ms,json=grantedUnixMs,proto3" json:"granted_unix_ms,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseInfo) Reset() {
	*x = LeaseInfo{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseInfo) ProtoMessage() {}

func (x *LeaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseInfo.ProtoReflect.Descriptor instead.
func (*LeaseInfo) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaseInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LeaseInfo) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaseInfo) GetGrantedUnixMs() int64 {
	if x != nil {
		return x.GrantedUnixMs
	}
	return 0
}

func (x *LeaseInfo) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type ListLeasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leases        []*LeaseInfo           `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesResponse) Reset() {
	*x = ListLeasesResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesResponse) ProtoMessage() {}

func (x *ListLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListLeasesResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{8}
}

func (x *ListLeasesResponse) GetLeases() []*LeaseInfo {
	if x != nil {
		return x.Leases
	}
	return nil
}

var File_clusdr_v1alpha1_leases_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_leases_proto_rawDesc = "" +
	"\n" +
	"\x1cclusdr/v1alpha1/leases.proto\x12\x0fclusdr.v1alpha1\"T\n" +
	"\x11GrantLeaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\"\xad\x01\n" +
	"\x12GrantLeaseResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"y\n" +
	"\x11RenewLeaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x15\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03R\x05ttlMs\"\x97\x01\n" +
	"\x12RenewLeaseResponse\x12\x18\n" +
	"\arenewed\x18\x01 \x01(\bR\arenewed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12(\n" +
	"\x10deadline_unix_ms\x18\x04 \x01(\x03R\x0edeadlineUnixMs\"c\n" +
	"\x12RevokeLeaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\"I\n" +
	"\x13RevokeLeaseResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListLeasesRequest\"\xac\x01\n" +
	"\tLeaseInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12&\n" +
	"\x0fgranted_unix_ms\x18\x04 \x01(\x03R\rgrantedUnixMs\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"H\n" +
	"\x12ListLeasesResponse\x122\n" +
	"\x06leases\x18\x01 \x03(\v2\x1a.clusdr.v1alpha1.LeaseInfoR\x06leases2\xde\x02\n" +
	"\fLeaseService\x12P\n" +
	"\x05Grant\x12\".clusdr.v1alpha1.GrantLeaseRequest\x1a#.clusdr.v1alpha1.GrantLeaseResponse\x12P\n" +
	"\x05Renew\x12\".clusdr.v1alpha1.RenewLeaseRequest\x1a#.clusdr.v1alpha1.RenewLeaseResponse\x12S\n" +
	"\x06Revoke\x12#.clusdr.v1alpha1.RevokeLeaseRequest\x1a$.clusdr.v1alpha1.RevokeLeaseResponse\x12U\n" +
	"\n" +
	"ListLeases\x12\".clusdr.v1alpha1.ListLeasesRequest\x1a#.clusdr.v1alpha1.ListLeasesResponseB>Z<github.com/odurgut/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_leases_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_leases_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_leases_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_leases_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_leases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_leases_proto_rawDesc), len(file_clusdr_v1alpha1_leases_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_leases_proto_rawDescData
}

var file_clusdr_v1alpha1_leases_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_clusdr_v1alpha1_leases_proto_goTypes = []any{
	(*GrantLeaseRequest)(nil),   // 0: clusdr.v1alpha1.GrantLeaseRequest
	(*GrantLeaseResponse)(nil),  // 1: clusdr.v1alpha1.GrantLeaseResponse
	(*RenewLeaseRequest)(nil),   // 2: clusdr.v1alpha1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),  // 3: clusdr.v1alpha1.RenewLeaseResponse
	(*RevokeLeaseRequest)(nil),  // 4: clusdr.v1alpha1.RevokeLeaseRequest
	(*RevokeLeaseResponse)(nil), // 5: clusdr.v1alpha1.RevokeLeaseResponse
	(*ListLeasesRequest)(nil),   // 6: clusdr.v1alpha1.ListLeasesRequest
	(*LeaseInfo)(nil),           // 7: clusdr.v1alpha1.LeaseInfo
	(*ListLeasesResponse)(nil),  // 8: clusdr.v1alpha1.ListLeasesResponse
}
var file_clusdr_v1alpha1_leases_proto_depIdxs = []int32{
	7, // 0: clusdr.v1alpha1.ListLeasesResponse.leases:type_name -> clusdr.v1alpha1.LeaseInfo
	0, // 1: clusdr.v1alpha1.LeaseService.Grant:input_type -> clusdr.v1alpha1.GrantLeaseRequest
	2, // 2: clusdr.v1alpha1.LeaseService.Renew:input_type -> clusdr.v1alpha1.RenewLeaseRequest
	4, // 3: clusdr.v1alpha1.LeaseService.Revoke:input_type -> clusdr.v1alpha1.RevokeLeaseRequest
	6, // 4: clusdr.v1alpha1.LeaseService.ListLeases:input_type -> clusdr.v1alpha1.ListLeasesRequest
	1, // 5: clusdr.v1alpha1.LeaseService.Grant:output_type -> clusdr.v1alpha1.GrantLeaseResponse
	3, // 6: clusdr.v1alpha1.LeaseService.Renew:output_type -> clusdr.v1alpha1.RenewLeaseResponse
	5, // 7: clusdr.v1alpha1.LeaseService.Revoke:output_type -> clusdr.v1alpha1.RevokeLeaseResponse
	8, // 8: clusdr.v1alpha1.LeaseService.ListLeases:output_type -> clusdr.v1alpha1.ListLeasesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_leases_proto_init() }
func file_clusdr_v1alpha1_leases_proto_init() {
	if File_clusdr_v1alpha1_leases_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_leases_proto_rawDesc), len(file_clusdr_v1alpha1_leases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_leases_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_leases_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_leases_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_leases_proto = out.File
	file_clusdr_v1alpha1_leases_proto_goTypes = nil
	file_clusdr_v1alpha1_leases_proto_depIdxs = nil
}
