// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.9
// source: clusdr/v1alpha1/leases.proto

package clusdrv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaseService_Grant_FullMethodName      = "/clusdr.v1alpha1.LeaseService/Grant"
	LeaseService_Renew_FullMethodName      = "/clusdr.v1alpha1.LeaseService/Renew"
	LeaseService_Revoke_FullMethodName     = "/clusdr.v1alpha1.LeaseService/Revoke"
	LeaseService_ListLeases_FullMethodName = "/clusdr.v1alpha1.LeaseService/ListLeases"
)

// LeaseServiceClient is the client API for LeaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LeaseService provides named TTL grants backed by Raft.
//
// A lease is lighter than a lock: Grant never blocks. The owner must Renew
// before the deadline or the leader expires the grant (lease.expired).
type LeaseServiceClient interface {
	Grant(ctx context.Context, in *GrantLeaseRequest, opts ...grpc.CallOption) (*GrantLeaseResponse, error)
	Renew(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error)
	Revoke(ctx context.Context, in *RevokeLeaseRequest, opts ...grpc.CallOption) (*RevokeLeaseResponse, error)
	ListLeases(ctx context.Context, in *ListLeasesRequest, opts ...grpc.CallOption) (*ListLeasesResponse, error)
}

type leaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaseServiceClient(cc grpc.ClientConnInterface) LeaseServiceClient {
	return &leaseServiceClient{cc}
}

func (c *leaseServiceClient) Grant(ctx context.Context, in *GrantLeaseRequest, opts ...grpc.CallOption) (*GrantLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantLeaseResponse)
	err := c.cc.Invoke(ctx, LeaseService_Grant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) Renew(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewLeaseResponse)
	err := c.cc.Invoke(ctx, LeaseService_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) Revoke(ctx context.Context, in *RevokeLeaseRequest, opts ...grpc.CallOption) (*RevokeLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeLeaseResponse)
	err := c.cc.Invoke(ctx, LeaseService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) ListLeases(ctx context.Context, in *ListLeasesRequest, opts ...grpc.CallOption) (*ListLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeasesResponse)
	err := c.cc.Invoke(ctx, LeaseService_ListLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaseServiceServer is the server API for LeaseService service.
// All implementations must embed UnimplementedLeaseServiceServer
// for forward compatibility.
//
// LeaseService provides named TTL grants backed by Raft.
//
// A lease is lighter than a lock: Grant never blocks. The owner must Renew
// before the deadline or the leader expires the grant (lease.expired).
type LeaseServiceServer interface {
	Grant(context.Context, *GrantLeaseRequest) (*GrantLeaseResponse, error)
	Renew(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error)
	Revoke(context.Context, *RevokeLeaseRequest) (*RevokeLeaseResponse, error)
	ListLeases(context.Context, *ListLeasesRequest) (*ListLeasesResponse, error)
	mustEmbedUnimplementedLeaseServiceServer()
}

// UnimplementedLeaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaseServiceServer struct{}

func (UnimplementedLeaseServiceServer) Grant(context.Context, *GrantLeaseRequest) (*GrantLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Grant not implemented")
}
func (UnimplementedLeaseServiceServer) Renew(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedLeaseServiceServer) Revoke(context.Context, *RevokeLeaseRequest) (*RevokeLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedLeaseServiceServer) ListLeases(context.Context, *ListLeasesRequest) (*ListLeasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeases not implemented")
}
func (UnimplementedLeaseServiceServer) mustEmbedUnimplementedLeaseServiceServer() {}
func (UnimplementedLeaseServiceServer) testEmbeddedByValue()                      {}

// UnsafeLeaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaseServiceServer will
// result in compilation errors.
type UnsafeLeaseServiceServer interface {
	mustEmbedUnimplementedLeaseServiceServer()
}

func RegisterLeaseServiceServer(s grpc.ServiceRegistrar, srv LeaseServiceServer) {
	// If the following call panics, it indicates UnimplementedLeaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaseService_ServiceDesc, srv)
}

func _LeaseService_Grant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).Grant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_Grant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).Grant(ctx, req.(*GrantLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).Renew(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).Revoke(ctx, req.(*RevokeLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_ListLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).ListLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_ListLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).ListLeases(ctx, req.(*ListLeasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaseService_ServiceDesc is the grpc.ServiceDesc for LeaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clusdr.v1alpha1.LeaseService",
	HandlerType: (*LeaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Grant",
			Handler:    _LeaseService_Grant_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _LeaseService_Renew_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _LeaseService_Revoke_Handler,
		},
		{
			MethodName: "ListLeases",
			Handler:    _LeaseService_ListLeases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clusdr/v1alpha1/leases.proto",
}
