// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: clusdr/v1alpha1/leases.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lease identity (1–128 chars: letters, digits, . _ -).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// owner is the node or client id. Empty → this daemon's node id.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// ttl_ms is the grant lifetime. 0 uses the daemon default (lease.ttl).
	TtlMs         int64 `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{0}
}

func (x *GrantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrantRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GrantRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type GrantResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Granted        bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Owner          string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrantResponse) Reset() {
	*x = GrantResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantResponse) ProtoMessage() {}

func (x *GrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantResponse.ProtoReflect.Descriptor instead.
func (*GrantResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{1}
}

func (x *GrantResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *GrantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GrantResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *GrantResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GrantResponse) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type LeaseServiceRenewRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner        string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FencingToken uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// ttl_ms replaces the remaining lifetime. 0 reuses the original TTL.
	TtlMs         int64 `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseServiceRenewRequest) Reset() {
	*x = LeaseServiceRenewRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseServiceRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseServiceRenewRequest) ProtoMessage() {}

func (x *LeaseServiceRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseServiceRenewRequest.ProtoReflect.Descriptor instead.
func (*LeaseServiceRenewRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{2}
}

func (x *LeaseServiceRenewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaseServiceRenewRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LeaseServiceRenewRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaseServiceRenewRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type LeaseServiceRenewResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Renewed        bool                   `protobuf:"varint,1,opt,name=renewed,proto3" json:"renewed,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,4,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseServiceRenewResponse) Reset() {
	*x = LeaseServiceRenewResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseServiceRenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseServiceRenewResponse) ProtoMessage() {}

func (x *LeaseServiceRenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseServiceRenewResponse.ProtoReflect.Descriptor instead.
func (*LeaseServiceRenewResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{3}
}

func (x *LeaseServiceRenewResponse) GetRenewed() bool {
	if x != nil {
		return x.Renewed
	}
	return false
}

func (x *LeaseServiceRenewResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LeaseServiceRenewResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaseServiceRenewResponse) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RevokeRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RevokeRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListLeasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesRequest) Reset() {
	*x = ListLeasesRequest{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesRequest) ProtoMessage() {}

func (x *ListLeasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesRequest.ProtoReflect.Descriptor instead.
func (*ListLeasesRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{6}
}

type LeaseInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner          string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	GrantedUnixMs  int64                  `protobuf:"varint,4,opt,name=granted_unix_ms,json=grantedUnixMs,proto3" json:"granted_unix_ms,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseInfo) Reset() {
	*x = LeaseInfo{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseInfo) ProtoMessage() {}

func (x *LeaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseInfo.ProtoReflect.Descriptor instead.
func (*LeaseInfo) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaseInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LeaseInfo) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LeaseInfo) GetGrantedUnixMs() int64 {
	if x != nil {
		return x.GrantedUnixMs
	}
	return 0
}

func (x *LeaseInfo) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type ListLeasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leases        []*LeaseInfo           `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesResponse) Reset() {
	*x = ListLeasesResponse{}
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesResponse) ProtoMessage() {}

func (x *ListLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_leases_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListLeasesResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_leases_proto_rawDescGZIP(), []int{8}
}

func (x *ListLeasesResponse) GetLeases() []*LeaseInfo {
	if x != nil {
		return x.Leases
	}
	return nil
}

var File_clusdr_v1alpha1_leases_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_leases_proto_rawDesc = "" +
	"\n" +
	"\x1cclusdr/v1alpha1/leases.proto\x12\x0fclusdr.v1alpha1\"O\n" +
	"\fGrantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\"\xa8\x01\n" +
	"\rGrantResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"\x80\x01\n" +
	"\x18LeaseServiceRenewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x15\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03R\x05ttlMs\"\x9e\x01\n" +
	"\x19LeaseServiceRenewResponse\x12\x18\n" +
	"\arenewed\x18\x01 \x01(\bR\arenewed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12(\n" +
	"\x10deadline_unix_ms\x18\x04 \x01(\x03R\x0edeadlineUnixMs\"^\n" +
	"\rRevokeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\"D\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListLeasesRequest\"\xac\x01\n" +
	"\tLeaseInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12&\n" +
	"\x0fgranted_unix_ms\x18\x04 \x01(\x03R\rgrantedUnixMs\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"H\n" +
	"\x12ListLeasesResponse\x122\n" +
	"\x06leases\x18\x01 \x03(\v2\x1a.clusdr.v1alpha1.LeaseInfoR\x06leases2\xd8\x02\n" +
	"\fLeaseService\x12F\n" +
	"\x05Grant\x12\x1d.clusdr.v1alpha1.GrantRequest\x1a\x1e.clusdr.v1alpha1.GrantResponse\x12^\n" +
	"\x05Renew\x12).clusdr.v1alpha1.LeaseServiceRenewRequest\x1a*.clusdr.v1alpha1.LeaseServiceRenewResponse\x12I\n" +
	"\x06Revoke\x12\x1e.clusdr.v1alpha1.RevokeRequest\x1a\x1f.clusdr.v1alpha1.RevokeResponse\x12U\n" +
	"\n" +
	"ListLeases\x12\".clusdr.v1alpha1.ListLeasesRequest\x1a#.clusdr.v1alpha1.ListLeasesResponseB=Z;github.com/clusdr/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_leases_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_leases_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_leases_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_leases_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_leases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_leases_proto_rawDesc), len(file_clusdr_v1alpha1_leases_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_leases_proto_rawDescData
}

var file_clusdr_v1alpha1_leases_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_clusdr_v1alpha1_leases_proto_goTypes = []any{
	(*GrantRequest)(nil),              // 0: clusdr.v1alpha1.GrantRequest
	(*GrantResponse)(nil),             // 1: clusdr.v1alpha1.GrantResponse
	(*LeaseServiceRenewRequest)(nil),  // 2: clusdr.v1alpha1.LeaseServiceRenewRequest
	(*LeaseServiceRenewResponse)(nil), // 3: clusdr.v1alpha1.LeaseServiceRenewResponse
	(*RevokeRequest)(nil),             // 4: clusdr.v1alpha1.RevokeRequest
	(*RevokeResponse)(nil),            // 5: clusdr.v1alpha1.RevokeResponse
	(*ListLeasesRequest)(nil),         // 6: clusdr.v1alpha1.ListLeasesRequest
	(*LeaseInfo)(nil),                 // 7: clusdr.v1alpha1.LeaseInfo
	(*ListLeasesResponse)(nil),        // 8: clusdr.v1alpha1.ListLeasesResponse
}
var file_clusdr_v1alpha1_leases_proto_depIdxs = []int32{
	7, // 0: clusdr.v1alpha1.ListLeasesResponse.leases:type_name -> clusdr.v1alpha1.LeaseInfo
	0, // 1: clusdr.v1alpha1.LeaseService.Grant:input_type -> clusdr.v1alpha1.GrantRequest
	2, // 2: clusdr.v1alpha1.LeaseService.Renew:input_type -> clusdr.v1alpha1.LeaseServiceRenewRequest
	4, // 3: clusdr.v1alpha1.LeaseService.Revoke:input_type -> clusdr.v1alpha1.RevokeRequest
	6, // 4: clusdr.v1alpha1.LeaseService.ListLeases:input_type -> clusdr.v1alpha1.ListLeasesRequest
	1, // 5: clusdr.v1alpha1.LeaseService.Grant:output_type -> clusdr.v1alpha1.GrantResponse
	3, // 6: clusdr.v1alpha1.LeaseService.Renew:output_type -> clusdr.v1alpha1.LeaseServiceRenewResponse
	5, // 7: clusdr.v1alpha1.LeaseService.Revoke:output_type -> clusdr.v1alpha1.RevokeResponse
	8, // 8: clusdr.v1alpha1.LeaseService.ListLeases:output_type -> clusdr.v1alpha1.ListLeasesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_leases_proto_init() }
func file_clusdr_v1alpha1_leases_proto_init() {
	if File_clusdr_v1alpha1_leases_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_leases_proto_rawDesc), len(file_clusdr_v1alpha1_leases_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_leases_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_leases_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_leases_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_leases_proto = out.File
	file_clusdr_v1alpha1_leases_proto_goTypes = nil
	file_clusdr_v1alpha1_leases_proto_depIdxs = nil
}
