// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: clusdr/v1alpha1/locks.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock identity (1–128 chars: letters, digits, . _ -).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// holder is the node or client id taking the lock. Empty → this daemon's node id.
	Holder string `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	// ttl_ms is the grant lifetime. 0 uses the daemon default (lock.ttl).
	TtlMs         int64 `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{0}
}

func (x *LockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LockRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LockRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type LockResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Acquired bool                   `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// fencing_token is a cluster-wide monotonic counter. Store it and pass it
	// to Unlock. A stale holder with an old token cannot release a new grant.
	FencingToken   uint64 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Holder         string `protobuf:"bytes,4,opt,name=holder,proto3" json:"holder,omitempty"`
	DeadlineUnixMs int64  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{1}
}

func (x *LockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *LockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LockResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LockResponse) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LockResponse) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type TryLockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the lock identity (1–128 chars: letters, digits, . _ -).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// holder is the node or client id taking the lock. Empty → this daemon's node id.
	Holder string `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	// ttl_ms is the grant lifetime. 0 uses the daemon default (lock.ttl).
	TtlMs         int64 `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TryLockRequest) Reset() {
	*x = TryLockRequest{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockRequest) ProtoMessage() {}

func (x *TryLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockRequest.ProtoReflect.Descriptor instead.
func (*TryLockRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{2}
}

func (x *TryLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TryLockRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *TryLockRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type TryLockResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acquired       bool                   `protobuf:"varint,1,opt,name=acquired,proto3" json:"acquired,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Holder         string                 `protobuf:"bytes,4,opt,name=holder,proto3" json:"holder,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TryLockResponse) Reset() {
	*x = TryLockResponse{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TryLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryLockResponse) ProtoMessage() {}

func (x *TryLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryLockResponse.ProtoReflect.Descriptor instead.
func (*TryLockResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{3}
}

func (x *TryLockResponse) GetAcquired() bool {
	if x != nil {
		return x.Acquired
	}
	return false
}

func (x *TryLockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TryLockResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *TryLockResponse) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *TryLockResponse) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type UnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Holder        string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockRequest.ProtoReflect.Descriptor instead.
func (*UnlockRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{4}
}

func (x *UnlockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnlockRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *UnlockRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockResponse.ProtoReflect.Descriptor instead.
func (*UnlockResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{5}
}

func (x *UnlockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *UnlockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LockServiceRenewRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Holder       string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	FencingToken uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	// ttl_ms replaces the remaining lifetime. 0 reuses the original TTL.
	TtlMs         int64 `protobuf:"varint,4,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockServiceRenewRequest) Reset() {
	*x = LockServiceRenewRequest{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockServiceRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockServiceRenewRequest) ProtoMessage() {}

func (x *LockServiceRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockServiceRenewRequest.ProtoReflect.Descriptor instead.
func (*LockServiceRenewRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{6}
}

func (x *LockServiceRenewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LockServiceRenewRequest) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LockServiceRenewRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LockServiceRenewRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

type LockServiceRenewResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Renewed        bool                   `protobuf:"varint,1,opt,name=renewed,proto3" json:"renewed,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,4,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockServiceRenewResponse) Reset() {
	*x = LockServiceRenewResponse{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockServiceRenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockServiceRenewResponse) ProtoMessage() {}

func (x *LockServiceRenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockServiceRenewResponse.ProtoReflect.Descriptor instead.
func (*LockServiceRenewResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{7}
}

func (x *LockServiceRenewResponse) GetRenewed() bool {
	if x != nil {
		return x.Renewed
	}
	return false
}

func (x *LockServiceRenewResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LockServiceRenewResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LockServiceRenewResponse) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type ListLocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocksRequest) Reset() {
	*x = ListLocksRequest{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksRequest) ProtoMessage() {}

func (x *ListLocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksRequest.ProtoReflect.Descriptor instead.
func (*ListLocksRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{8}
}

type LockInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Holder         string                 `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	AcquiredUnixMs int64                  `protobuf:"varint,4,opt,name=acquired_unix_ms,json=acquiredUnixMs,proto3" json:"acquired_unix_ms,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,5,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockInfo) Reset() {
	*x = LockInfo{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockInfo) ProtoMessage() {}

func (x *LockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockInfo.ProtoReflect.Descriptor instead.
func (*LockInfo) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{9}
}

func (x *LockInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LockInfo) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LockInfo) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *LockInfo) GetAcquiredUnixMs() int64 {
	if x != nil {
		return x.AcquiredUnixMs
	}
	return 0
}

func (x *LockInfo) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

type ListLocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locks         []*LockInfo            `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocksResponse) Reset() {
	*x = ListLocksResponse{}
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocksResponse) ProtoMessage() {}

func (x *ListLocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_locks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocksResponse.ProtoReflect.Descriptor instead.
func (*ListLocksResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_locks_proto_rawDescGZIP(), []int{10}
}

func (x *ListLocksResponse) GetLocks() []*LockInfo {
	if x != nil {
		return x.Locks
	}
	return nil
}

var File_clusdr_v1alpha1_locks_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_locks_proto_rawDesc = "" +
	"\n" +
	"\x1bclusdr/v1alpha1/locks.proto\x12\x0fclusdr.v1alpha1\"P\n" +
	"\vLockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\"\xab\x01\n" +
	"\fLockResponse\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x16\n" +
	"\x06holder\x18\x04 \x01(\tR\x06holder\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"S\n" +
	"\x0eTryLockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\"\xae\x01\n" +
	"\x0fTryLockResponse\x12\x1a\n" +
	"\bacquired\x18\x01 \x01(\bR\bacquired\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x16\n" +
	"\x06holder\x18\x04 \x01(\tR\x06holder\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"`\n" +
	"\rUnlockRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\"F\n" +
	"\x0eUnlockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x81\x01\n" +
	"\x17LockServiceRenewRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x15\n" +
	"\x06ttl_ms\x18\x04 \x01(\x03R\x05ttlMs\"\x9d\x01\n" +
	"\x18LockServiceRenewResponse\x12\x18\n" +
	"\arenewed\x18\x01 \x01(\bR\arenewed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12(\n" +
	"\x10deadline_unix_ms\x18\x04 \x01(\x03R\x0edeadlineUnixMs\"\x12\n" +
	"\x10ListLocksRequest\"\xaf\x01\n" +
	"\bLockInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12(\n" +
	"\x10acquired_unix_ms\x18\x04 \x01(\x03R\x0eacquiredUnixMs\x12(\n" +
	"\x10deadline_unix_ms\x18\x05 \x01(\x03R\x0edeadlineUnixMs\"D\n" +
	"\x11ListLocksResponse\x12/\n" +
	"\x05locks\x18\x01 \x03(\v2\x19.clusdr.v1alpha1.LockInfoR\x05locks2\x9d\x03\n" +
	"\vLockService\x12C\n" +
	"\x04Lock\x12\x1c.clusdr.v1alpha1.LockRequest\x1a\x1d.clusdr.v1alpha1.LockResponse\x12L\n" +
	"\aTryLock\x12\x1f.clusdr.v1alpha1.TryLockRequest\x1a .clusdr.v1alpha1.TryLockResponse\x12I\n" +
	"\x06Unlock\x12\x1e.clusdr.v1alpha1.UnlockRequest\x1a\x1f.clusdr.v1alpha1.UnlockResponse\x12\\\n" +
	"\x05Renew\x12(.clusdr.v1alpha1.LockServiceRenewRequest\x1a).clusdr.v1alpha1.LockServiceRenewResponse\x12R\n" +
	"\tListLocks\x12!.clusdr.v1alpha1.ListLocksRequest\x1a\".clusdr.v1alpha1.ListLocksResponseB=Z;github.com/clusdr/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_locks_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_locks_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_locks_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_locks_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_locks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_locks_proto_rawDesc), len(file_clusdr_v1alpha1_locks_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_locks_proto_rawDescData
}

var file_clusdr_v1alpha1_locks_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_clusdr_v1alpha1_locks_proto_goTypes = []any{
	(*LockRequest)(nil),              // 0: clusdr.v1alpha1.LockRequest
	(*LockResponse)(nil),             // 1: clusdr.v1alpha1.LockResponse
	(*TryLockRequest)(nil),           // 2: clusdr.v1alpha1.TryLockRequest
	(*TryLockResponse)(nil),          // 3: clusdr.v1alpha1.TryLockResponse
	(*UnlockRequest)(nil),            // 4: clusdr.v1alpha1.UnlockRequest
	(*UnlockResponse)(nil),           // 5: clusdr.v1alpha1.UnlockResponse
	(*LockServiceRenewRequest)(nil),  // 6: clusdr.v1alpha1.LockServiceRenewRequest
	(*LockServiceRenewResponse)(nil), // 7: clusdr.v1alpha1.LockServiceRenewResponse
	(*ListLocksRequest)(nil),         // 8: clusdr.v1alpha1.ListLocksRequest
	(*LockInfo)(nil),                 // 9: clusdr.v1alpha1.LockInfo
	(*ListLocksResponse)(nil),        // 10: clusdr.v1alpha1.ListLocksResponse
}
var file_clusdr_v1alpha1_locks_proto_depIdxs = []int32{
	9,  // 0: clusdr.v1alpha1.ListLocksResponse.locks:type_name -> clusdr.v1alpha1.LockInfo
	0,  // 1: clusdr.v1alpha1.LockService.Lock:input_type -> clusdr.v1alpha1.LockRequest
	2,  // 2: clusdr.v1alpha1.LockService.TryLock:input_type -> clusdr.v1alpha1.TryLockRequest
	4,  // 3: clusdr.v1alpha1.LockService.Unlock:input_type -> clusdr.v1alpha1.UnlockRequest
	6,  // 4: clusdr.v1alpha1.LockService.Renew:input_type -> clusdr.v1alpha1.LockServiceRenewRequest
	8,  // 5: clusdr.v1alpha1.LockService.ListLocks:input_type -> clusdr.v1alpha1.ListLocksRequest
	1,  // 6: clusdr.v1alpha1.LockService.Lock:output_type -> clusdr.v1alpha1.LockResponse
	3,  // 7: clusdr.v1alpha1.LockService.TryLock:output_type -> clusdr.v1alpha1.TryLockResponse
	5,  // 8: clusdr.v1alpha1.LockService.Unlock:output_type -> clusdr.v1alpha1.UnlockResponse
	7,  // 9: clusdr.v1alpha1.LockService.Renew:output_type -> clusdr.v1alpha1.LockServiceRenewResponse
	10, // 10: clusdr.v1alpha1.LockService.ListLocks:output_type -> clusdr.v1alpha1.ListLocksResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_locks_proto_init() }
func file_clusdr_v1alpha1_locks_proto_init() {
	if File_clusdr_v1alpha1_locks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_locks_proto_rawDesc), len(file_clusdr_v1alpha1_locks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_locks_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_locks_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_locks_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_locks_proto = out.File
	file_clusdr_v1alpha1_locks_proto_goTypes = nil
	file_clusdr_v1alpha1_locks_proto_depIdxs = nil
}
