// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.9
// source: clusdr/v1alpha1/membership.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Member describes a single node in the cluster.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier of this node.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// address is the gRPC Runtime API address of this node.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// status is the current liveness of this node: alive | leaving | dead.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// leader is true when this node is the current Raft leader.
	Leader bool `protobuf:"varint,4,opt,name=leader,proto3" json:"leader,omitempty"`
	// role is voter | observer. Empty means voter.
	Role          string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_membership_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Member) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *Member) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_membership_proto_rawDescGZIP(), []int{1}
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_membership_proto_rawDescGZIP(), []int{2}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type GetLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderRequest) Reset() {
	*x = GetLeaderRequest{}
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderRequest) ProtoMessage() {}

func (x *GetLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_membership_proto_rawDescGZIP(), []int{3}
}

type GetLeaderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// leader_id is the node ID of the current leader. Empty if no leader.
	LeaderId string `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// address is the gRPC address of the leader node.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderResponse) Reset() {
	*x = GetLeaderResponse{}
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderResponse) ProtoMessage() {}

func (x *GetLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_membership_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeaderResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *GetLeaderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_clusdr_v1alpha1_membership_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_membership_proto_rawDesc = "" +
	"\n" +
	" clusdr/v1alpha1/membership.proto\x12\x0fclusdr.v1alpha1\"v\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06leader\x18\x04 \x01(\bR\x06leader\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x14\n" +
	"\x12ListMembersRequest\"H\n" +
	"\x13ListMembersResponse\x121\n" +
	"\amembers\x18\x01 \x03(\v2\x17.clusdr.v1alpha1.MemberR\amembers\"\x12\n" +
	"\x10GetLeaderRequest\"J\n" +
	"\x11GetLeaderResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2\xc1\x01\n" +
	"\x11MembershipService\x12X\n" +
	"\vListMembers\x12#.clusdr.v1alpha1.ListMembersRequest\x1a$.clusdr.v1alpha1.ListMembersResponse\x12R\n" +
	"\tGetLeader\x12!.clusdr.v1alpha1.GetLeaderRequest\x1a\".clusdr.v1alpha1.GetLeaderResponseB>Z<github.com/odurgut/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_membership_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_membership_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_membership_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_membership_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_membership_proto_rawDesc), len(file_clusdr_v1alpha1_membership_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_membership_proto_rawDescData
}

var file_clusdr_v1alpha1_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clusdr_v1alpha1_membership_proto_goTypes = []any{
	(*Member)(nil),              // 0: clusdr.v1alpha1.Member
	(*ListMembersRequest)(nil),  // 1: clusdr.v1alpha1.ListMembersRequest
	(*ListMembersResponse)(nil), // 2: clusdr.v1alpha1.ListMembersResponse
	(*GetLeaderRequest)(nil),    // 3: clusdr.v1alpha1.GetLeaderRequest
	(*GetLeaderResponse)(nil),   // 4: clusdr.v1alpha1.GetLeaderResponse
}
var file_clusdr_v1alpha1_membership_proto_depIdxs = []int32{
	0, // 0: clusdr.v1alpha1.ListMembersResponse.members:type_name -> clusdr.v1alpha1.Member
	1, // 1: clusdr.v1alpha1.MembershipService.ListMembers:input_type -> clusdr.v1alpha1.ListMembersRequest
	3, // 2: clusdr.v1alpha1.MembershipService.GetLeader:input_type -> clusdr.v1alpha1.GetLeaderRequest
	2, // 3: clusdr.v1alpha1.MembershipService.ListMembers:output_type -> clusdr.v1alpha1.ListMembersResponse
	4, // 4: clusdr.v1alpha1.MembershipService.GetLeader:output_type -> clusdr.v1alpha1.GetLeaderResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_membership_proto_init() }
func file_clusdr_v1alpha1_membership_proto_init() {
	if File_clusdr_v1alpha1_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_membership_proto_rawDesc), len(file_clusdr_v1alpha1_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_membership_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_membership_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_membership_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_membership_proto = out.File
	file_clusdr_v1alpha1_membership_proto_goTypes = nil
	file_clusdr_v1alpha1_membership_proto_depIdxs = nil
}
