// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.9
// source: clusdr/v1alpha1/watch.proto

package clusdrv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchRequest optionally filters the event stream.
type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If non-empty, only events whose type matches one of these strings are
	// forwarded.  Supported types: "member.join", "member.left",
	// "leader.changed".  An empty list means "all events".
	// Protocol events (watch.sync, watch.gap) are always delivered.
	EventTypes []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// last_seq is the last live sequence number the client processed.
	// On reconnect the server sends a state snapshot, then a watch.sync
	// (seq = current bus seq) and a watch.gap if last_seq is behind.
	// 0 means "no prior seq" (first connect).
	LastSeq uint64 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	// topics filters custom events by routing key (without the "custom."
	// prefix). When non-empty, only custom.<topic> events for listed topics
	// are forwarded — membership snapshot/live events are omitted.
	// Protocol events (watch.sync, watch.gap) are always delivered.
	// An empty list means "do not filter by topic".
	Topics        []string `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_clusdr_v1alpha1_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *WatchRequest) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *WatchRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// WatchResponse carries a single cluster event.
type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is a dot-separated event kind: "member.join", "member.left",
	// "leader.changed".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// source is the node ID that caused the event.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// payload is optional JSON-encoded detail (e.g. {"address":"host:port"}).
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// timestamp_unix_ms is when the event occurred (milliseconds since epoch).
	TimestampUnixMs int64 `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// seq is the global monotonically increasing sequence number assigned by the
	// event bus.  Snapshot events carry seq=0.  watch.sync carries the bus seq
	// the snapshot is consistent with.  A jump in live seq (or a watch.gap
	// event) means the client missed events and should treat the snapshot as
	// source of truth.
	Seq           uint64 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_clusdr_v1alpha1_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clusdr_v1alpha1_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_clusdr_v1alpha1_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WatchResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WatchResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WatchResponse) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *WatchResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_clusdr_v1alpha1_watch_proto protoreflect.FileDescriptor

const file_clusdr_v1alpha1_watch_proto_rawDesc = "" +
	"\n" +
	"\x1bclusdr/v1alpha1/watch.proto\x12\x0fclusdr.v1alpha1\"b\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\"\x93\x01\n" +
	"\rWatchResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq2X\n" +
	"\fWatchService\x12H\n" +
	"\x05Watch\x12\x1d.clusdr.v1alpha1.WatchRequest\x1a\x1e.clusdr.v1alpha1.WatchResponse0\x01B>Z<github.com/durguto/clusdr/api/clusdr/v1alpha1;clusdrv1alpha1b\x06proto3"

var (
	file_clusdr_v1alpha1_watch_proto_rawDescOnce sync.Once
	file_clusdr_v1alpha1_watch_proto_rawDescData []byte
)

func file_clusdr_v1alpha1_watch_proto_rawDescGZIP() []byte {
	file_clusdr_v1alpha1_watch_proto_rawDescOnce.Do(func() {
		file_clusdr_v1alpha1_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_watch_proto_rawDesc), len(file_clusdr_v1alpha1_watch_proto_rawDesc)))
	})
	return file_clusdr_v1alpha1_watch_proto_rawDescData
}

var file_clusdr_v1alpha1_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clusdr_v1alpha1_watch_proto_goTypes = []any{
	(*WatchRequest)(nil),  // 0: clusdr.v1alpha1.WatchRequest
	(*WatchResponse)(nil), // 1: clusdr.v1alpha1.WatchResponse
}
var file_clusdr_v1alpha1_watch_proto_depIdxs = []int32{
	0, // 0: clusdr.v1alpha1.WatchService.Watch:input_type -> clusdr.v1alpha1.WatchRequest
	1, // 1: clusdr.v1alpha1.WatchService.Watch:output_type -> clusdr.v1alpha1.WatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clusdr_v1alpha1_watch_proto_init() }
func file_clusdr_v1alpha1_watch_proto_init() {
	if File_clusdr_v1alpha1_watch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusdr_v1alpha1_watch_proto_rawDesc), len(file_clusdr_v1alpha1_watch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clusdr_v1alpha1_watch_proto_goTypes,
		DependencyIndexes: file_clusdr_v1alpha1_watch_proto_depIdxs,
		MessageInfos:      file_clusdr_v1alpha1_watch_proto_msgTypes,
	}.Build()
	File_clusdr_v1alpha1_watch_proto = out.File
	file_clusdr_v1alpha1_watch_proto_goTypes = nil
	file_clusdr_v1alpha1_watch_proto_depIdxs = nil
}
