package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/durguto/clusdr/internal/config"
	"github.com/durguto/clusdr/internal/mtls"
	"github.com/durguto/clusdr/internal/pki"
	"github.com/durguto/clusdr/internal/store"
	"github.com/durguto/clusdr/internal/uid"
)

func newInitCmd(f *rootFlags) *cobra.Command {
	var force bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a new Clusdr cluster",
		Long: `Initialize a new Clusdr cluster on this node.

Generates a cluster ID, node ID, cluster CA, and a one-time join token.
Writes clusdr.yaml and persists identity plus PKI to the local state
database. Run this once on the first node. Other nodes join with
'clusdr join --token <token> <addr>'.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			path := f.configPath

			if _, err := os.Stat(path); err == nil && !force {
				return fmt.Errorf("config file %q already exists (use --force to overwrite)", path)
			}

			clusterID, err := uid.New()
			if err != nil {
				return fmt.Errorf("generate cluster id: %w", err)
			}
			nodeID, err := uid.New()
			if err != nil {
				return fmt.Errorf("generate node id: %w", err)
			}

			// Write YAML config.
			type initConfig struct {
				Node struct {
					ID   string `yaml:"id"`
					Addr string `yaml:"addr"`
				} `yaml:"node"`
				Cluster struct {
					ID string `yaml:"id"`
				} `yaml:"cluster"`
				Log struct {
					Level  string `yaml:"level"`
					Format string `yaml:"format"`
				} `yaml:"log"`
			}

			var cfg initConfig
			cfg.Node.ID = nodeID
			cfg.Node.Addr = "0.0.0.0:7947"
			cfg.Cluster.ID = clusterID
			cfg.Log.Level = "info"
			cfg.Log.Format = "text"

			data, err := yaml.Marshal(cfg)
			if err != nil {
				return fmt.Errorf("marshal config: %w", err)
			}

			header := "# Clusdr configuration\n# Generated by 'clusdr init'\n# See docs/reference/configuration.md for all options.\n\n"
			if err := os.WriteFile(path, append([]byte(header), data...), 0o600); err != nil {
				return fmt.Errorf("write config %q: %w", path, err)
			}

			// Persist identity to BoltDB state database.
			// Use the resolved data dir (default or from env/flag).
			resolved, err := config.LoadFrom(path, os.Getenv)
			if err != nil {
				return fmt.Errorf("reload config: %w", err)
			}

			st, err := store.Open(resolved.Data.Dir)
			if err != nil {
				return fmt.Errorf("open store: %w", err)
			}
			defer st.Close()

			if err := st.SaveIdentity(nodeID, clusterID); err != nil {
				return fmt.Errorf("save identity: %w", err)
			}

			bundle, joinToken, err := pki.Generate(clusterID, nodeID)
			if err != nil {
				return fmt.Errorf("generate cluster CA: %w", err)
			}
			if err := st.SaveCerts(store.Certs{
				CACert:        bundle.CACert,
				CAKey:         bundle.CAKey,
				NodeCert:      bundle.NodeCert,
				NodeKey:       bundle.NodeKey,
				JoinTokenHash: bundle.JoinTokenHash,
			}); err != nil {
				return fmt.Errorf("save certs: %w", err)
			}

			if err := mtls.WriteFiles(resolved.Data.Dir, bundle.CACert, bundle.NodeCert, bundle.NodeKey); err != nil {
				return fmt.Errorf("write cert files: %w", err)
			}
			caPath := filepath.Join(resolved.Data.Dir, mtls.CAFile)

			fp, err := pki.Fingerprint(bundle.CACert)
			if err != nil {
				return fmt.Errorf("ca fingerprint: %w", err)
			}

			out := cmd.OutOrStdout()
			fmt.Fprintln(out, "cluster initialized")
			fmt.Fprintln(out)
			fmt.Fprintf(out, "  cluster id      : %s\n", clusterID)
			fmt.Fprintf(out, "  node id         : %s\n", nodeID)
			fmt.Fprintf(out, "  config          : %s\n", path)
			fmt.Fprintf(out, "  data dir        : %s\n", resolved.Data.Dir)
			fmt.Fprintf(out, "  ca cert         : %s\n", caPath)
			fmt.Fprintf(out, "  ca fingerprint  : %s\n", fp)
			fmt.Fprintln(out)
			fmt.Fprintf(out, "  join token      : %s\n", joinToken)
			fmt.Fprintln(out)
			fmt.Fprintln(out, "  The join token is shown only once. Store it securely.")
			fmt.Fprintln(out)
			fmt.Fprintln(out, "next steps:")
			fmt.Fprintln(out, "  clusdr start --bootstrap        start this node as the first voter")
			fmt.Fprintln(out, "  clusdr certs show               inspect the cluster CA")
			fmt.Fprintln(out, "  clusdr join --token <token> <addr>")

			return nil
		},
	}

	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing config file")
	return cmd
}
