name: Proto

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    name: Buf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1
        with:
          version: "1.73.0"
          token: ${{ secrets.BUF_TOKEN }}
          push_create_visibility: public
          push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) && secrets.BUF_TOKEN != '' }}

      - name: Generate
        if: github.event_name != 'delete'
        run: |
          buf generate
          git diff --exit-code -- api/
